
@host =localhost:8080
@contentType = application/json

@opportunityId=KWNaMorO

### List Available Oportunities
POST http://{{host}}/services/opportunities?offset=0&size=20
Content-Type: {{contentType}}

{
  "query":{
    "and": [{
      "or": [{
        "skill/role": {
          "text": "React",
          "experience": "potential-to-develop"
        }
      }]
    }, {
      "or": [{
        "organization": {
          "term": "Stripe"
        }
      }]
    }]
  }
}

### Get Oportunity Detail
GET http://{{host}}/services/opportunities/{{opportunityId}}
Content-Type: {{contentType}}
